### ISSUE TITLE
Wrong icons

### ISSUE THREAD

**Issue by md1023** [jtbm37/all-the-icons-dired#13] opened 2018-02-09 14:57 UTC
I run GNU Emacs 25.3.2. Here's snip of list-packages:

```
  all-the-icons      20180125.757  installed             A library for inserting Developer icons
  all-the-icons-d... 20170418.1431 installed             Shows icons for each file in dired mode
```

I did update `all-the-icons`, now I see lighting icon instead of usual folder. Package was updated along with `neotree` package that I installed.

**Comment by leodumont** [comment] 2018-02-13 09:30
I'm afraid I encounter something similar:
![selection_004](https://user-images.githubusercontent.com/908404/36142309-fc2a749a-10a7-11e8-8448-c56beef0355b.png)

Version of Emacs i'm running:
GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21) of 2017-09-22
And from Melpa:
all-the-icons dired 20170418.1431
all-the-icons 20180125.757

**Comment by jtbm37** [comment] 2018-02-13 10:48
@leodumont @md1023 are you sure you did follow the installation instructions from https://github.com/domtronn/all-the-icons.el ?

**Comment by md1023** [comment] 2018-02-13 13:12
@jtbm37, icons were proper prior to update. Neotree showed icons properly after update, then I removed neotree and it didn't help. I'll try to install from scratch later today.

**Comment by jtbm37** [comment] 2018-02-13 13:22
I am on the same version of the modes as you are but it is working.
However I am on `GNU Emacs 26.0.50.2 (x86_64-unknown-linux-gnu, GTK+ Version 3.18.9) of 2016-12-12` that I compiled from source.

**Comment by leodumont** [comment] 2018-02-13 14:40
@jtbm37 Same here, the fonts are well installed. By the way, in some dired buffers some of the icons are displaying as expected:
![selection_006](https://user-images.githubusercontent.com/908404/36155269-3a026cf6-10d4-11e8-9630-c9b73ce56583.png)

**Comment by jtbm37** [comment] 2018-02-13 19:45
I logged on another computer with `GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21) of 2017-09-22, modified by Debian` and it is displayed correctly too.

**Comment by md1023** [comment] 2018-02-14 12:22
![screenshot from 2018-02-14 15-19-06](https://user-images.githubusercontent.com/1615319/36203979-8b2dd2de-119a-11e8-88da-d09ecc167ef0.png)

Sorry, I'm unlucky. Installed Manjaro Gnome 17 yesterday to try. Same issue on my Ubuntu 16.04 LXDE and Fedora 26 installations.

**Comment by jtbm37** [comment] 2018-02-15 07:47
Open the scratch buffer and evaluate (`C-x e` on the last closing bracket) the following:

`(insert (all-the-icons-octicon "file-directory" :v-adjust all-the-icons-dired-v-adjust :face 'all-the-icons-dired-dir-face))` 

If the inserted icon is not a directory then the issue is with https://github.com/domtronn/all-the-icons.el
Possible related issues: 
https://github.com/domtronn/all-the-icons.el/issues/99
https://github.com/domtronn/all-the-icons.el/issues/107

**Closed** 2018-02-15 08:18 UTC
